<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit8177f6f5513bf0ac10a5f3cc0ff3ceb1
{
    public static $prefixLengthsPsr4 = array (
        'B' => 
        array (
            'BoogieFromZk\\AgoraToken\\' => 24,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'BoogieFromZk\\AgoraToken\\' => 
        array (
            0 => __DIR__ . '/..' . '/boogiefromzk/agora-token/src',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit8177f6f5513bf0ac10a5f3cc0ff3ceb1::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit8177f6f5513bf0ac10a5f3cc0ff3ceb1::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInit8177f6f5513bf0ac10a5f3cc0ff3ceb1::$classMap;

        }, null, ClassLoader::class);
    }
}
